apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: job-queue
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: job-queue-ksa
      containers:
        - name: worker
          image: us-central1-docker.pkg.dev/job-queue-engine/job-queue-images/worker:IMAGE_TAG
          envFrom:
            - secretRef:
                name: job-queue-secrets
          env:
            - name: ENVIRONMENT
              value: production
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
